### ISSUE TITLE
Fix Airflow stats

### ISSUE THREAD

**Issue by ryw** [astronomerio/incubator-airflow#25]
@schnie commented on [Thu Mar 22 2018](https://github.com/astronomerio/astronomer/issues/40)

Our grafana dashboard for the scheduler/workers shows some inaccurate numbers. See: https://issues.apache.org/jira/browse/AIRFLOW-774.

We should fix those bugs on our fork, release it, and submit a PR to apache.

This is kind of important, but since people aren't actually using it in production, there are no complaints. We should get ahead of it.

**Comment by tedmiston** [comment]
Closing in favor of https://github.com/astronomerio/incubator-airflow/issues/29
